#!/bin/bash
[[ $0 != $BASH_SOURCE ]] && SCRIPT_PATH=$(realpath $BASH_SOURCE) || SCRIPT_PATH="`readlink -f "$0"`"
ENV_DIR="`dirname "$SCRIPT_PATH"`"

bash -rcfile <(echo "
  source ~/.bashrc
  PS1=\"(olympe-python3) \${PS1}\"
  source ${ENV_DIR}/setenv
")
