#!/bin/bash

#Program to output a system information page

TITLE="System Information Report $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, BY $USER"

cat << _EOF_
<html>
 <head>
     <title>$title</title>
 </head>
 <body>
    <h1>$title</h1>
    <p>$TIMESTAMP</p>
    $(report_uptime)
    $(report_disk_space)
    $(report_home_space)
 </body>
</html>
_EOF_

